### ISSUE TITLE
Relying on stable packages?

### ISSUE THREAD

**Issue by ffMathy** [originalmoose/Typescript.Definitions.Tools#1]
When I try to run `dotnet restore` for my project which has this as its tool dependency, I get an error that `Microsoft.Extensions.CommandLineUtils` could not be resolved.

It is trying to resolve some alpha version which is not even present in the NuGet feed (https://www.nuget.org/packages/Microsoft.Extensions.CommandLineUtils/1.0.0).

Is there any chance we could maybe use 1.0.0 instead, which is stable? What is the reason for the alpha version being used instead?

**Comment by originalmoose** [comment]
Good catch

> Is there any chance we could maybe use 1.0.0 instead, which is stable?

I'll work on putting out a 1.0.1 release which will use the correct stable packages.

> What is the reason for the alpha version being used instead?

This started mainly as a learning exercise to figure out the .net core tooling and I used the EF Core tools as an example. I probably was looking at their dev branch when I first started and probably just copied some of the dependencies (I believe I had their dev nuget feed added to my dev machine at the time - recently reformated so not really sure if I had it in there or not).

Once I decided to publish I should have reverted to stable packages before doing so and that's on me... hopefully I'll have something out shortly.

**Comment by originalmoose** [comment]
Just published 1.0.1 to nuget so you should be able to update (might not be in the search just yet but if you set the version manually in the package.json it should download). Since I just reformatted I went ahead and created a base .net core web app and tried the 1.0.0 version and got the restore error. 1.0.1 restored just fine however so you should be good to go!

Please let me know if you have any other issues or any feature requests.
